// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "daemontalk/internal/i18n"

func AboutPage(ui i18n.UI, lang string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"container-page py-8 sm:py-12\"><div class=\"max-w-3xl\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if lang == "id" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<h1 class=\"display text-3xl font-bold text-text mb-6\">Tentang Daemontalk</h1><div class=\"prose prose-sm md:prose-base text-text space-y-4\"><p>Daemontalk adalah buku catatan terbuka dan portofolio tempat saya mendokumentasikan proses belajar seputar Go backend, Python, sistem operasi Linux, dan arsitektur backend.</p><h3>Tujuan Situs</h3><p>Situs ini saya bangun sebagai wadah portofolio serta arsip catatan kuliah sistem informasi. Alih-alih hanya mencatat teori, saya berusaha menguji langsung cara kerja sistem, menganalisis perilaku runtime, dan merangkum eksperimen kode yang dapat dijalankan secara nyata.</p><h3>Pendekatan Belajar</h3><p>Saya lebih menyukai catatan yang ringkas dan langsung pada inti masalah. Setiap tulisan di sini mengutamakan reproduksibilitas: mulai dari perintah shell, skrip pengujian performa, hingga arsitektur kode sumber yang terbuka untuk dipelajari bersama.</p><h3>Teknologi di Balik Layar</h3><p>Web ini dibangun sebagai satu berkas biner Go mandiri menggunakan router chi, mesin templat templ, dan TailwindCSS. Semuanya dirender di sisi server tanpa framework JavaScript berat agar tetap ringan, cepat diakses, dan ramah sumber daya.</p></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<h1 class=\"display text-3xl font-bold text-text mb-6\">About Daemontalk</h1><div class=\"prose prose-sm md:prose-base text-text space-y-4\"><p>Daemontalk is an open technology notebook and personal portfolio where I document my learning journey in Go backend development, Python, Linux systems, and backend architecture.</p><h3>Purpose</h3><p>I built this site to serve as a working archive for my information systems studies and practical projects. Rather than keeping abstract notes, I focus on testing system mechanics directly, inspecting runtime behavior, and writing reproducible technical explorations.</p><h3>Learning Approach</h3><p>I prefer concise notes that get straight to the technical core. Every article emphasizes practical verification: shell diagnostics, performance experiments, and open-source code snippets designed to be run and tested.</p><h3>Technology Stack</h3><p>The site runs as a single Go binary powered by chi for routing, templ for type-safe HTML generation, and TailwindCSS. Everything is server-rendered with zero heavy client-side JavaScript to keep the reading experience fast, simple, and resource-friendly.</p></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
